DOMAIN = "node_energy"
PLATFORMS = ["sensor"]

CONF_NAME = "name"
CONF_BATTERY_ENTITY = "battery_entity"
CONF_VOLTAGE_ENTITY = "voltage_entity"
CONF_WEATHER_ENTITY = "weather_entity"
CONF_ANALYSIS_START = "analysis_start"
CONF_START_HOUR = "start_hour"
CONF_START_DATE = "start_date"
CONF_CELLS_CURRENT = "cells_current"
CONF_CELL_MAH = "cell_mah"
CONF_CELL_V = "cell_v"
CONF_HORIZON_DAYS = "horizon_days"

DEFAULT_NAME = "Battery Telemetry Forecast"
DEFAULT_START_HOUR = 16
DEFAULT_CELLS_CURRENT = 2
DEFAULT_CELL_MAH = 3500
DEFAULT_CELL_V = 3.7
DEFAULT_HORIZON_DAYS = 7
DEFAULT_MODEL_WINDOW_DAYS = 90
DEFAULT_PAYLOAD_WINDOW_DAYS = 30
UPDATE_INTERVAL_MINUTES = 30

ATTR_HISTORY_SOC = "history_soc"
ATTR_HISTORY_VOLTAGE = "history_voltage"
ATTR_HISTORY_WEATHER = "history_weather"
ATTR_INTERVALS = "intervals"
ATTR_FORECAST = "forecast"
ATTR_MODEL = "model"
ATTR_META = "meta"
ATTR_APEX_SERIES = "apex_series"
ATTR_NO_SUN_RUNTIME_DAYS = "no_sun_runtime_days"
ATTR_NET_POWER_NOW_W = "net_power_now_w"
ATTR_NET_POWER_AVG_24H_W = "net_power_avg_24h_w"
ATTR_CHARGE_POWER_NOW_W = "charge_power_now_w"
ATTR_DISCHARGE_POWER_NOW_W = "discharge_power_now_w"
ATTR_ENERGY_CHARGED_KWH_TOTAL = "energy_charged_kwh_total"
ATTR_ENERGY_DISCHARGED_KWH_TOTAL = "energy_discharged_kwh_total"
ATTR_FULL_CHARGE_ETA_HOURS = "full_charge_eta_hours"
ATTR_FULL_CHARGE_AT = "full_charge_at"
